### ISSUE TITLE
Split not building in Swift 5 - Enum associated values

### ISSUE THREAD

**Issue by AnthonyMillerSF** [splitio/ios-client#112]
In Swift 5, we get a build error using Split in the file Dynamic Target
`Enum element with associated values must have at least one associated value`

![Screen Shot 2019-05-30 at 2 04 28 PM](https://user-images.githubusercontent.com/49412465/58664636-e43e8380-82e3-11e9-954f-6a57a5a997f1.png)

The cases with no associated values don't really need the `()` I think. But if you can't change that, could you please add `swift_version = '4.2'` to your podspec so that it builds this pod with Swift 4.2 until this is fixed for Swift 5?

Thanks!

**Comment by NicoZelaya** [comment]
Hi @AnthonyMillerSF! 

Our sincere apologies for the inconveniences and thank you very much for flagging! 
We'll be looking at it with our iOS team soon and will let you know here once we have any update. 

Best regards,
Nico.

**Comment by chillaq** [comment]
Hi Anthony, issue is resolved and pushed in latest build.

Thanks
Bilal
