### ISSUE TITLE
impressionListener causing crash on 2.4.0

### ISSUE THREAD

**Issue by bull-xu** [splitio/ios-client#128]
Updated to v2.4.0 and the impressionListener caused crash.

**Comment by NicoZelaya** [comment]
Hi @bull-xu,

I'm very sorry to hear that. Could you please share the stack trace of the exception with us? Or any other information that could help us identify the issue. 

Thanks in advance,
Nico.

**Comment by bull-xu** [comment]
Hi @NicoZelaya it looks the crash no longer happens since I used Xcode 11. I didn't test it with old Xcode (10.3).
