### ISSUE TITLE
Request for Swift package manager support

### ISSUE THREAD

**Issue by laeur** [splitio/ios-client#139]
Good day!
Please, add support for Swift Package Manager. 
Thank you!

**Comment by sourabhguptavc** [comment]
@NicoZelaya Is there any update on this issue. When we can have swift package manager support

**Comment by bwhiteley** [comment]
Any updates on this? With Xcode 12 released today, I suspect some folks will be keen on moving to SwiftPM soon.

**Comment by bsarrazin** [comment]
This is the way.

When can we expect support for SPM?

**Comment by matcartmill** [comment]
Any updates here? I'm trying to move a project to using SPM and the only blocker I have at the moment is Split.

**Comment by NicoZelaya** [comment]
Hey everyone! My most sincere apologies this kind of fell under our radar. 

Many thanks @bsarrazin for contributing ! We'll pick up your PR, get the tests running in the CI, review everything and aim to have it released next week.
Will keep an eye on this one and let you know as soon as it's all done.

Thank you all for your patience,
Nico.

**Comment by MauricioDomenech** [comment]
Any news about this ??

**Comment by bsarrazin** [comment]
@MauricioDomenech the `master` branch contains the `Package.swift` file. You should be able to consume Split as an SPM package now.
@NicoZelaya I think it's worth closing this issue?
