### ISSUE TITLE
Make the package version easily accessible

### ISSUE THREAD

**Issue by nsillik** [splitio/ios-client#140]
Any chance there you could add a static way of getting the version of the Split ios-client? We want to include that in attributes and other analytics that we're using.

As of right now the only place to get the current package version is through the `SplitFactory#version` property. By the time I'm needing that data I've already disposed of the factory.

I did see that you export `Split.SplitVersionNumber`, but that is currently returning `Double(1.0)` for me. I also noticed that there is a `Version` class which exposes a static version string in `Split/Common/Utils/Version.swift`, but this isn't exposed (it's `internal`, not public). 

I also noticed that the `Info.plist`'s version hasn't been updated for a while and is currently set to 1.2. This should probably be updated to match the cocoapod's version.

Thanks!

**Comment by NicoZelaya** [comment]
Hi @nsillik !

We've released the patch version 2.5.1 which should allow you to access the sdkVersion property through DefaultSplitFactory.

```swift
import Split
let version = DefaultSplitFactory.sdkVersion
```

Would you mind giving it a try and letting us know how it goes? We'll keep the issue open for now until we hear back from you.

Thanks in advance!
Nico.
