### ISSUE TITLE
Heap corruption on implementation SDK

### ISSUE THREAD

**Issue by kleiberjp** [splitio/ios-client#147]
We're presenting many issues on memory corruption by split, here is one of the stack-trace found it on our crash report 

`Crashed: split-event-queue
0  libobjc.A.dylib                0x1bf1bf030 objc_retain + 16
1  Grability                      0x104c14ed0 specialized SyncDictionaryCollectionWrapper.count.getter + 25852936 (<compiler-generated>:25852936)
2  Grability                      0x104bcac7c DefaultImpressionsManager.appendHit() + 74 (DefaultImpressionsManager.swift:74)
3  Grability                      0x104bcb14c closure #1 in DefaultImpressionsManager.createPollingManager(dispatchGroup:) + 66 (DefaultImpressionsManager.swift:66)
4  Grability                      0x104bfe228 closure #1 in PollingManager.triggerPollAction() + 25759584 (<compiler-generated>:25759584)
5  Grability                      0x10203cbd8 thunk for @escaping @callee_guaranteed () -> () + 4370992088 (<compiler-generated>:4370992088)
6  libdispatch.dylib              0x1bf149610 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x1bf14a184 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1bf0f6464 _dispatch_lane_serial_drain$VARIANT$mp + 608
9  libdispatch.dylib              0x1bf0f6e58 _dispatch_lane_invoke$VARIANT$mp + 420
10 libdispatch.dylib              0x1bf100340 _dispatch_workloop_worker_thread + 588
11 libsystem_pthread.dylib        0x1bf199fa4 _pthread_wqthread + 276
12 libsystem_pthread.dylib        0x1bf19cae0 start_wqthread + 8`

in addition, some evidence of the leaks memory founded on our app
<img width="901" alt="Screen Shot 2019-12-23 at 2 24 13 PM" src="https://user-images.githubusercontent.com/8697226/72396068-842d0e00-3709-11ea-8c31-7785cbeea4cf.png">
<img width="438" alt="Screen Shot 2019-12-23 at 2 24 17 PM" src="https://user-images.githubusercontent.com/8697226/72396069-842d0e00-3709-11ea-8937-2d5a2f904e5f.png">

**Comment by NicoZelaya** [comment]
Hi @kleiberjp,

our sincere apologies for the inconveniences this is causing to you and your team. 
Let's follow up on this topic through the currently opened support ticket so we can better exchange debug information there, we'll be sending an update soon. 

Either way I'll keep this issue open for now until we can resolve it. 

Best regards,
Nico.

**Comment by kaseyb002** [comment]
Any updates on this fix by chance? We seeing a significant number of crashes in this same spot.

**Comment by NicoZelaya** [comment]
@kaseyb002 hi Kasey,

I'm closing this ticket as the originally reported issue was confirmed to be fixed back in the day but please reopen or open a new one with more information if you're still experiencing any problems, we'll take a look from our end.

Nico.
