### ISSUE TITLE
Propagate Split 'update' events

### ISSUE THREAD

**Issue by IanKeen** [splitio/ios-client#150]
It appears the `DefaultRefreshableSplitFetcher` is [polling](https://github.com/splitio/ios-client/blob/master/Split/FetcherEngine/Refresh/DefaultRefreshableSplitFetcher.swift#L92) and aware of split updates. However the events are [internal](https://github.com/splitio/ios-client/blob/master/Split/Events/SplitEventsManager.swift#L144-L148) and not available to consumers.

Are there any plans to push thees out so consumers could potentially react to new data in realtime?

**Comment by chillaq** [comment]
Hi Ian, currently we only have this capability in Javascript SDK, I will submit a feature request on your behalf to have a SDK_UPDATE event that will fire when there is a change in a Split definition.

If you have any additional business case for the importance of this feature and which company you are working with, it will help with prioritizing the feature request.

Thanks
Bilal

**Comment by IanKeen** [comment]
Thanks for that! No additional/specific requirements at this time... We are migrating to Split from LaunchDarkly which provided this feature, it something we'd like to have eventually to allow us to build more 'realtime' based flagging in the future.

**Comment by chillaq** [comment]
Understood, thanks Ian.
