### ISSUE TITLE
Can't Archive framework using Xcode 12

### ISSUE THREAD

**Issue by dvshelley** [splitio/ios-client#164]
When I try to archive the Split framework, I get this error:
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in YAMLParser.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
1) At first I thought the problem was that the “valid architectures” in the build settings had something old. In fact, it was set to the default. Other apps show the same thing. Setting this value to something causes the setting to show up for the first time in the project file. Removing all the items from the list fixes the build error.

When I select Build/Archive non-device, it shows (armv7/arm64). Newly created apps just show (arm64). I don’t know what controls this.

2) Setting the IPHONEOS_DEPLOYMENT_TARGET to 11.0 also fixes the problem.

3) I suspect the problem may in fact be a bug in Xcode 12. I don't think either of the above is going to be "the right thing" for Split. This seems like the sort of thing that you should jump on immediately while you have the opportunity to engage with Apple about it before the new tooling is released.

**Comment by chillaq** [comment]
Hi, thanks for the info, we are checking this issue now.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Daniel, Just want to let you know, I got a similar issue from another customer and they had the archive error when testing  the project using Fastlane on iOS version 9. 
They added “ONLY_ACTIVE_ARCH = YES;”,  into the pbxproj file and that fixed the issue.

Thanks
Bilal

**Comment by chillaq** [comment]
HI Daniel, just want to confirm if the suggestion above worked for you.

Thanks
Bilal

**Comment by dvshelley** [comment]
It worked perfectly. Thanks for figuring this out.
