### ISSUE TITLE
Crashing in CoreData

### ISSUE THREAD

**Issue by PorterHoskins** [splitio/ios-client#248]
We are getting a bunch of crashes with the new background CoreData syncing on 2.11.x. Usually happens when we bring the app to the foreground. The crash is happening in CoreDataHelper when you persist the managed object context.

**Comment by agustinona** [comment]
Hi Porter,

Thanks for bringing this to our attention.
Are you able to consistently repro the issue? In that case would you mind sharing debug logs or details for us to do it on our end so we can look into it?

**Comment by PorterHoskins** [comment]
Here is an example. You guys are violating the threading policy for CoreData.

<img width="641" alt="Screen Shot 2021-06-19 at 2 06 47 PM" src="https://user-images.githubusercontent.com/5604819/122654290-a77e9880-d107-11eb-8c3a-e1243a57c117.png">

If you add `com.apple.CoreData.ConcurrencyDebug = 1` to your environment variables, you will get asserts when you perform a operation incorrectly.

**Comment by agustinona** [comment]
Thank you. I can repro now. I will escalate to engineering.

**Comment by chillaq** [comment]
Hi @PorterHoskins ,  iOS SDK 2.11.2 version is released with a fix for this issue.

Thanks
Bilal
