### ISSUE TITLE
Unable to build using Xcode 13 beta 4 - register(forTaskWithIdentifier:using:launchHandler:)' is unavailable...

### ISSUE THREAD

**Issue by joshbuhler** [splitio/ios-client#265]
We are importing the Split SDK via Swift Package Manager. Currently using Split v2.11.3.

When attempting to build using Xcode 13 beta 4 we get the following error:

`SplitBgSynchronizer.swift:55:50: error: 'register(forTaskWithIdentifier:using:launchHandler:)' is unavailable in application extensions for iOS: Only the host application may register launch handlers
            let success = BGTaskScheduler.shared.register(
                                                 ^~~~~~~~
BackgroundTasks.BGTaskScheduler:11:15: note: 'register(forTaskWithIdentifier:using:launchHandler:)' has been explicitly marked unavailable here
    open func register(forTaskWithIdentifier identifier: String, using queue: DispatchQueue?, launchHandler: @escaping (BGTask) -> Void) -> Bool`

**Comment by chillaq** [comment]
Hi @joshbuhler, thanks for the info, as a workaround, do you get the same issue if you use pods to add the Split SDK?

**Comment by joshbuhler** [comment]
@chillaq - I have not tried using pods. We do not use pods for any other dependencies (currently migrating away from Carthage to SPM). We've been using SPM with success in Xcode 12 and would prefer not to introduce a new workflow for this one dependency only.

**Comment by lihao6485** [comment]
Same issue while using Split SDK via SPM.

I have tried to use Split SDK via Carthage, it is working fine.

**Comment by joshbuhler** [comment]
With Xcode 13 beta 5 (13A5212g) I'm no longer seeing this issue. I'll reopen this if it shows up again.
