### ISSUE TITLE
Feature Request: Single Split getTreament API call

### ISSUE THREAD

**Issue by PorterHoskins** [splitio/ios-client#267]
Setting up the `SplitClient` has a decent overhead. We would like to make a single `getTreatment` call to the server without incurring the setup cost of the entire client.

This is important when relying on split when booting up the app. Waiting milliseconds for a single API call would be a significantly better user experience then waiting for the current setup time required by the SDK.

**Comment by chillaq** [comment]
Hi @PorterHoskins , you can deploy Split Evaluator as a service, this is a http service wrapped around NodeJS SDK, once its up and running, you only need to use get http requests to fetch treatments.
Checkout the doc link: https://help.split.io/hc/en-us/articles/360020037072-Split-evaluator

**Comment by PorterHoskins** [comment]
Thanks. That should work great
