### ISSUE TITLE
App start time slow down up to 8 secs

### ISSUE THREAD

**Issue by Tokta** [splitio/ios-client#286]
Hello, we recently introduced the SDK to our mobile app (both iOS and Android). Now we activated our first feature flag value and we got notified by Firebase performances that the app start time is increasing, in some cases up to 8 secs. 
<img width="762" alt="Screenshot 2021-10-08 at 16 36 26" src="https://user-images.githubusercontent.com/5616444/136575939-5e0749f5-2333-4593-8e62-9ef130fc74f2.png">

By digging a bit, we see that the split.io sdk is mentioned by firebase:
<img width="1156" alt="Screenshot 2021-10-08 at 16 19 06" src="https://user-images.githubusercontent.com/5616444/136576228-b840eea3-a4d8-4af3-8f32-db5c2263be8e.png">

Does exist some configuration you recommend to avoid this pick at the app start?

**Comment by chillaq** [comment]
Hi @Tokta 

I'm following up on this issue. Do you still require any assistance?

Thanks,
Bilal

**Comment by chillaq** [comment]
Hi @Tokta

I'm following up on this issue. It has been a while since I heard back, do you still require any assistance?

Thanks,
Bilal

**Comment by Tokta** [comment]
Hi, sorry for my late response. By updating the SDK to the last version the problem disappeared. Thank you for your support.
