### ISSUE TITLE
Crash in SDK

### ISSUE THREAD

**Issue by SajjadKharrazi** [splitio/ios-client#371]
we are using 2.13.2 version and we have crash reports like these:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/7239983/184014064-9802953a-c47a-4d92-8ae2-c8167d19d1d1.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/7239983/184014230-4fd572ca-4dac-47a4-b196-e3c8c0b44aee.png">

**Comment by chillaq** [comment]
Hi @SajjadKharrazi , thanks for the info, will check with the team.

**Comment by chillaq** [comment]
Hi @SajjadKharrazi , I would like to continue working on this issue in a support ticket, could you please send an email with the details to support@split.io ?
We will respond from there.

Thanks
Bilal

**Comment by javrudsky** [comment]
Hi @SajjadKharrazi, I'm closing out this ticket. If we can be of further assistance on this topic, feel free to reopen the issue.
