### ISSUE TITLE
Crashes in SDK after updating from 2.11 to 2.16.2

### ISSUE THREAD

**Issue by gsbernstein** [splitio/ios-client#382]
I'm seeing 6 new crash types showing up in our crashlytics in the split SDK since updating from 2.11 to 2.16.2.

<img width="904" alt="Screenshot 2022-10-17 at 5 11 09 PM" src="https://user-images.githubusercontent.com/6655924/196306268-851bcb6a-3444-4c99-9bad-15d6ae21b5c5.png">

Most seem related to DefaultPushNotificationManager either connecting or disconnecting.

<img width="602" alt="Screenshot 2022-10-17 at 5 10 50 PM" src="https://user-images.githubusercontent.com/6655924/196306239-a768dda4-466c-46a4-8569-6715a95e0db1.png">

Unfortunately we haven't been able to reproduce them and don't know the conditions under which they occur, but they account for 62 of our 66 crashes in the last week (94%), so I'm probably going to roll back the update until you have a probable fix.

**Comment by agustinona** [comment]
Hi @gsbernstein,

Thanks for reporting this. I'm moving this into a support ticket and will be reaching out to you via email.

Best,
Agus

**Comment by charlie-q-tw** [comment]
@agustinona we're experiencing similar crashes, can we be notified when a fix is available?

**Comment by agustinona** [comment]
@charlie-q-tw of course. 

I was not able to identify your Split user email. Could you reach out to us at support@split.io so that a support ticket is opened for you for better tracking?

**Comment by agustinona** [comment]
@gsbernstein @charlie-q-tw,

We have released version 2.18.1 of our SDK with a fix for issues related to streaming disconnections (changelog: https://github.com/splitio/ios-client/blob/master/CHANGES.txt).
 
Could you upgrade and confirm this fixed the issue for you?

**Comment by javrudsky** [comment]
This issue was closed because it has been inactive for more than two months.
