### ISSUE TITLE
Can SplitIO SDK for iOS be used in AppExtension?

### ISSUE THREAD

**Issue by danibachar** [splitio/ios-client#405]
Dear development team,

It seems like the registration of Background tasks is not allowed from AppExtensions
Specifically the usage of this [API](https://github.com/splitio/ios-client/blob/eed66e051543c68d954089a891e347e10b2381b1/Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift#L56)

I'd hope to be able to use split from within AppExtenision, and wonder if we can work on an API update to allow delegating this code to the nesting application

Also, correct me if I'm wrong, but the plist key for the bb task-id and the actual capability as described [here](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app) will be required to allow the usage of this SDK within an AppExtension

**Comment by danibachar** [comment]
A link to a repo with two example projects is available [here](https://github.com/danibachar/SplitIO-BGTaskScheduler-register)

Note - the compilation error is happening only when using cocoapods.
If we introduce the SDK using SPM there is no compilation error, but only a crash when using the specific API from within the extensions - hence I guess this bug is less relevant to consumers via SPM

**Comment by hbqdev** [comment]
Hi @danibachar 
We have communicated the above to our development team, we will review this feature request and will have further updates if necessary.

Regards,

**Comment by franek-box** [comment]
@hbqdev Do you have any ETA for this issue to be fixed? It is affecting our project too.

**Comment by franek-box** [comment]
@hbqdev Do you have any ETA for this issue to be fixed?
