### ISSUE TITLE
Getting live updates when making update to a `split`

### ISSUE THREAD

**Issue by danibachar** [splitio/ios-client#411]
Dear development team,

If I understand correctly, the split sdk supports live updates.
In the [docs](https://help.split.io/hc/en-us/articles/360020401491-iOS-SDK) I saw this example
```
client.on(event: SplitEvent.sdkUpdated) {
  // fired each time the client state change. 
  // For example, when a Split or a Segment changes.
  // Do some stuff on main thread
}
```
Which seems like the right way to listen to updates.
But when I register to it, it will not fire events if I add a treatment to a split / remove or change the default value...
Trying to look into the SDK testing and examples didn't help.

I tried to set the different flags that seems related to cache
```
config.impressionRefreshRate = 1
config.featuresRefreshRate = 1
config.segmentsRefreshRate = 1
config.eventsPushRate = 1
config.metricsPushRate = 1
config.logLevel = .debug
```

And only saw these logs
```
["INFO", "SplitSDK", "Split SDK client for key 123 initialized!"]
["DEBUG", "SplitSDK", "Fetching segments"]
["DEBUG", "SplitSDK", "Fetching split definitions"]
["INFO", "SplitSDK", "Split definitions have been updated"]
["DEBUG", "SplitSDK", "Fetching split definitions"]
["INFO", "SplitSDK", "Split definitions have been updated"]
["DEBUG", "SplitSDK", "Streaming authentication success"]
["DEBUG", "SplitSDK", "Sending impressions"]
["INFO", "SplitSDK", "Impression posted successfully"]
```

The weird thing is that I have a testing screen that fetches the treatment using this API
```
func getTreatment(_ split: String, attributes: [String: Any]?) -> String
```

And when I change the default value for example to the `split` and publish the changes I do see the value updates (but it only when I explicitly checks against the `getTreatment`. While I would expect to also get an update in some listener.

See split screenshots
<img width="1272" alt="Screen Shot 2022-12-08 at 10 27 14 AM" src="https://user-images.githubusercontent.com/6380777/206523471-8f4ca32c-6794-4662-9262-56a5fbe8fbdd.png">
<img width="1273" alt="Screen Shot 2022-12-08 at 10 27 05 AM" src="https://user-images.githubusercontent.com/6380777/206523474-2c7f46ee-7820-4a31-b511-6455d0d03dbb.png">

I also see the updates in the split log

<img width="1266" alt="Screen Shot 2022-12-07 at 4 19 27 PM" src="https://user-images.githubusercontent.com/6380777/206533517-a7e8fb6b-a70e-4092-964d-8739632243c4.png">

See my testing screen recording after I change the value in the split dashboard

https://user-images.githubusercontent.com/6380777/206523626-63497183-a30a-40e0-83e4-4c1af3b6d2bb.MP4

Maybe I'm miss understand on how to do it? Maybe I need to use the impression listener?

**Comment by hbqdev** [comment]
Hi @danibachar 
By default there's a delay when updating the split, the sync will happen after about 30 seconds.

Further more since you are using mobile SDK, please see also https://help.split.io/hc/en-us/articles/360059049411-Mobile-and-Web-SDK-Split-changes-roll-out-slowly-to-user-devices-

Tbank you and Regards

**Comment by danibachar** [comment]
Thanks for the prompt reply. When you say a 60 seconds delay is that for this code snippet to happen?
```
client.on(event: SplitEvent.sdkUpdated) {
  // fired each time the client state change. 
  // For example, when a Split or a Segment changes.
  // Do some stuff on main thread
}
```

Because when I changed the values on the dashboard and queried with this function
```
func getTreatment(_ split: String, attributes: [String: Any]?) -> String
```

I saw the changes almost immediately - as shown in the video

**Comment by hbqdev** [comment]
Hi @danibachar 

The updates usually won't get to the SDK immediately, It depends on the CDN, when the CDN will not make successive calls to split origin to fetch the cache update, it will add a min delay of 60 seconds.

When you trigger getTreatment call, this forces an update so that's why you see the results, otherwise the getTreatment will be triggered when the cache is updated. 

Therefore, it is expected that you will see a slight delay, if the results don't show up at all then that would be a different issue.

Thank you and Regards,
Tin Tran

**Comment by hbqdev** [comment]
hi @danibachar 
Just checking, do you still need help for this issue?

thank you

**Comment by danibachar** [comment]
Thanks @hbqdev - I do, I didn't have the time to build an example project which replicates the issue.
I'm trying to understand, how can one know when the treatment value is changing on runtime?
Do we need to actively call `getTreatment`? Isn't there is a websocket that gets events from the server and propagate them using the SDK?

**Comment by danibachar** [comment]
@hbqdev - maybe someone can direct me on when will I get events when I register to the SDKs `func on(event: Split.SplitEvent, execute action: @escaping Split.SplitAction)` where `event = .sdkUpdated`?
Because I cannot make it get called when I played around with the default value of the split

**Comment by hbqdev** [comment]
Hi @danibachar 
It is correct that you can expect the sdkUpdated event to fire every time the split definitions are updated. 
However, we want to clarify that while the event will let you know when new definitions are available, it won’t update any treatments for you. You will still need to trigger a getTreatment evaluation from within the closure and update the components accordingly.

Can you please share with us the SDK version and the code snippet you are using where you setup the event Listener?

If possible can you also send an email to support@split.io so we can continue assisting you in the proper channel.

Regards

**Comment by hbqdev** [comment]
Hi @danibachar 
We tried with our latest SDK and were not able to reproduce your issue, we can see the event sdkUpdated got fired from our local test.

Can you try upgrading your SDK to the latest version and see if the issue is solved?

Thank you

**Comment by hbqdev** [comment]
Hi @danibachar 
Since we haven't heard from you in awhile, and since our attempt at reproducing this issue has not been successful, we will close this issue for now.

If you still need help in the future, we encourage you to send an email to support@split.io for better assistance.

Regards
