### ISSUE TITLE
not able to set bundle in SPM project

### ISSUE THREAD

**Issue by rahulrkp** [splitio/ios-client#481]
below is the code to build factory for localhost
let builder = DefaultSplitFactoryBuilder()
        let apiKey: String = "localhost"
        let key: Key = Key(matchingKey: apiKey)
        print("config =\(config.description)")
        let factory = builder.setApiKey("localhost").setKey(key).setConfig(config).build()

but split is always reading from Bundle.main but in SPM project file is in different bundle
can you please let me know how to set bundle
here is my local host file path - /Users/Library/Developer/Xcode/DerivedData/ios-myproj-cceikjkiikazawgewbbaikhzvsif/Build/Products/Debug-iphonesimulator/myproj_myprojTests.bundle/localhost.yaml
and split is reading from below path-
po bundle
NSBundle </Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents> (loaded)

Can you please let me know how to set SPM test bundle .

**Comment by hbqdev** [comment]
Hi @rahulrkp 

We see a support ticket opened in Zendesk for this issue, so we will continue communicating with that.

Regards
