### ISSUE TITLE
Split failing to build on CircleCI

### ISSUE THREAD

**Issue by dsrees** [splitio/ios-client#57]
I'm still investigating this issue myself, but I wanted to open this in case anyone has come across a similar problem.

Our builds on CircleCI started failing once the Split SDK was added. Here is the output from the log
```
/Users/distiller/project/Pods/Split/Split/Impressions/Impression.swift:11:15: error: type 'Impression' does not conform to protocol 'Decodable'
public struct Impression: Codable {
              ^
Swift.Decodable:9:12: note: protocol requires initializer 'init(from:)' with type 'Decodable'
    public init(from decoder: Decoder) throws
           ^
/Users/distiller/project/Pods/Split/Split/Impressions/Impression.swift:19:16: note: cannot automatically synthesize 'Decodable' because 'attributes' does not have a matching CodingKey and does not have a default value
    public var attributes: [String: Any]?
```

I'm not seeing this compile error when building from Xcode or when I run the same command locally that CCI is running. 

Any thoughts?

**Comment by SenhorCastor** [comment]
Hi dsrees,

Sorry for the inconveniences. 

We haven't seen that before,  Our team is taking a look, see if we can reproduce and find the root cause. Will keep this updated.

Fer

**Comment by javrudsky** [comment]
Hi dsrees,
Could you tell me please what is the xcode version in your circleci config.yml?
I'm trying to reproduce the issue locally and I think that could help.
Thank you,
Javier

**Comment by dsrees** [comment]
@javrudsky 
```
macos:
      xcode: "9.0"
```

thanks for looking into this

**Comment by dsrees** [comment]
Running 9.4.1 locally. I'll try updating CCI to use the same version as well

**Comment by dsrees** [comment]
@javrudsky Upgrading xcode to 9.4.1 seems to have done the trick! Thank you for looking into this and helping me figure it out.

Thanks for making this sdk and maintaining it well!

**Comment by javrudsky** [comment]
Great! Glad to help you
