### ISSUE TITLE
SemVer Attributes

### ISSUE THREAD

**Issue by ay8s** [splitio/ios-client#597]
Based on the documentation I'm sending Semantic Version Strings as attributes. These don't automatically show up in Split.io but I'm able to input the attribute name and use the SemVer matcher. 

However I feel like I'm missing a step somewhere as I'm unable to get it to ever return true. A app version, adjusted to an integer is working perfectly fine but we can run into issues.

Is there a undocumented way of setting and setting SemVer attributes?

![CleanShot 2024-11-12 at 15 54 02](https://github.com/user-attachments/assets/cf19705e-9c4f-4ddf-b4d7-2b2be6b2ab02)

**Comment by IngaAlma** [comment]
Hi,
 Can you please specify what SDK version you are using?
What attribute are you passing in the test, and what treatment was returned by the SDK?
Please send the full SDK configuration and how you are using the attributes in your code?
 
Thanks,
Inga

**Comment by ay8s** [comment]
Realized we had Split's Package locked to a version lower than the one required. Looks like it's working smoothly with the package updated to v3.0.
